name: "PR Examples Build"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'examples/**'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            testAdditionalJavaVersions: true
            coverage: true
    steps:
      - uses: actions/checkout@v2
      - id: setup-java-8
        name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jre
      - id: setup-java-11
        name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: clean check fatJar
          build-root-directory: examples
      - run: java -cp examples/sdk-usage/build/libs/opentelemetry-examples-sdk-usage-all-0.1.0-SNAPSHOT.jar io.opentelemetry.sdk.example.ConfigureSpanProcessorExample
